python main_spin.py --run 1
python main_spin.py --run 2
python main_spin.py --run 3
python main_spin.py --run 4
python main_spin.py --run 5
python main_spin.py --run 6
python main_spin.py --run 7
python main_spin.py --run 8
python main_spin.py --run 9
python main_spin.py --run 10